ARG NGINX_VERSION=1.26

FROM nginx:${NGINX_VERSION}-alpine-slim

#CUSTOM Labels
LABEL maintainer="Smriti Dubey"
LABEL version="1.0"
LABEL description="A simple Nginx application"

COPY index.html /usr/share/nginx/html