FROM nginx
LABEL Name="Smriti"
LABEL Description="About Dokcer ports"
COPY index.html /usr/share/nginx/html


================================================
PS C:\Users\T0283993\Desktop\Docker Codes\11_Docker_Ports> docker ps
CONTAINER ID   IMAGE           COMMAND                  CREATED         STATUS         PORTS                   NAMES
20e96890af5b   port-image:v1   "/docker-entrypoint.…"   7 seconds ago   Up 7 seconds   0.0.0.0:52063->80/tcp   port-container
PS C:\Users\T0283993\Desktop\Docker Codes\11_Docker_Ports> docker images
REPOSITORY   TAG       IMAGE ID       CREATED         SIZE 
port-image   v1        73e37a862b41   3 minutes ago   279MB
PS C:\Users\T0283993\Desktop\Docker Codes\11_Docker_Ports> 
